data_args:
    batch_size: 4
    train_years: [2017,2018,2019,2020,2021,2022]
    val_years: [2023]
    test_years: [2024]

    data_dir: '/data/zzn/insitu/nips'
    embedding_dir: '/data/zzn/insitu/nips'
    climatology_dir: '/data/zzn/insitu/nips/climatology.npy'
    input_length: 1
    output_length: 1

model_args:
    hidden_size: 64
    learning_rate: 0.001
    num_workers: 16
    t_max: 500
    head: 4